Add API ref for new endpoints
getlago/lago-docs pull request #16
Opened 2022-07-11 13:19 UTC by lovrocolic

2022-07-11 14:02 UTC, sarkissianraffi requested changes
Sidebar positions need to be reviewed. Nothing blocking the release but could be messy. All endpoints seem fine to me.

2022-07-11 14:02 UTC, sarkissianraffi commented on docs/api/10_invoices/get-all-invoices.mdx
> +sidebar_position: 8
Sidebar position should be `1`

2022-07-11 14:02 UTC, sarkissianraffi commented on docs/api/10_invoices/get-invoice.mdx
> +sidebar_position: 7
Sidebar position should be `2`

2022-07-11 14:02 UTC, sarkissianraffi commented on docs/api/13_organizations/update-organization.mdx
> +sidebar_position: 3
Sidebar position should be `2`

2022-07-12 15:41 UTC, lovrocolic commented
> Sidebar positions need to be reviewed. Nothing blocking the release but could be messy. All endpoints seem fine to me.

As discussed offline, final version in this branch is correct so I'm resolving comments

2022-07-13 16:05 UTC, sarkissianraffi approved these changes

2022-07-13 16:06 UTC, merged